Repository prgrms-fe-devcourse/FEDC5_brewers_hyunju, pull requests merged in 2024-01, with the labels that each got.

#14 [13] 댓글, 알림, 검색 커스텀 훅 구현
  src/hooks/api/comment/useCreateComment.ts
  src/hooks/api/comment/useDeleteComment.ts
  src/hooks/api/notification/useCreateNotification.ts
  src/hooks/api/notification/useGetNotification.ts
  src/hooks/api/notification/useReadNotification.ts
  src/hooks/api/search/useSearchAll.ts
  src/hooks/api/search/useSearchUsers.ts
  src/utils/handleError.ts
Labels: Feat

#19 [18] storybook 테스팅을 위한 다크모드 구현 방식 변경
  .storybook/main.ts
  .storybook/preview.ts
  index.html
  package-lock.json
  package.json
  src/colors.css
  src/index.css
  src/stories/Colors.mdx
Labels: Style, Test

#24 [21] pull-request-template.md 파일 위치 이동 및 상위 폴더 삭제
  .github/pull-request-template.md
Labels: Refactor

#26 [17] storybook 경로 별칭 인식 안됨 버그 해결
  .storybook/main.ts
  .storybook/preview.ts
Labels: Bug, Fix, Chore

#27 [20] 리코일 환경 설정
  src/App.tsx
  src/stories/Colors.mdx
Labels: Feat

#30 [23] 재사용 컴포넌트 Text, Flex, Conatiner 생성
  src/components/common/Container.tsx
  src/components/common/Flex.tsx
  src/components/common/Text.tsx
  src/constants/design.ts
  src/stories/Container.stories.tsx
  src/stories/Flex.stories.tsx
  src/stories/Text.stories.tsx
  src/types/design/color.ts
  src/types/design/container.ts
  src/types/design/font.ts
Labels: Feat

#33 [22] Image 재사용 컴포넌트 구현
  src/components/common/Image/index.tsx
  src/hooks/useIntersectionObserver.ts
  src/stories/components/Image.stories.tsx
Labels: Feat

#45 [44] stylelint `custom-property-pattern` 규칙 비활성화
  .stylelintrc.js
Labels: Chore

#41 [40] @tabler/icons-react 설치
  package-lock.json
  package.json
  src/stories/Icon.stories.tsx
Labels: Style, Chore

#59 [42] SUIT 폰트 적용
  index.html
  src/index.css
Labels: Style

#50 [47] Avatar 컴포넌트 구현
  src/components/common/Avatar.tsx
  src/components/common/Image/index.tsx
  src/constants/design.ts
  src/stories/Avatar.stories.tsx
  src/types/design/avatar.ts
  src/utils/handleSizeUnit.ts
Labels: Feat

#62 [46] Button 재사용 컴포넌트 구현
  src/components/common/Button.tsx
  src/constants/design.ts
  src/stories/Button.stories.tsx
  src/types/design/button.ts
  src/types/design/color.ts
Labels: Feat

#39 [37] Skeleton 재사용 컴포넌트 구현
  src/components/common/Skeleton.stories.tsx
  src/components/common/Skeleton.tsx
Labels: Feat

#54 [25] Input 컴포넌트 구현
  src/components/input/Input.tsx
  src/stories/components/Input.stories.tsx
Labels: Feat

#48 [36] Radio Button 컴포넌트 구현
  src/components/RadioGroup/Radio.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/stories/components/Radio.stories.tsx
  src/stories/components/RadioGroup.stories.tsx
Labels: Feat

#73 [69] Modal 컴포넌트 구현
  src/components/common/Modal/ModalBody.tsx
  src/components/common/Modal/ModalHeader.tsx
  src/components/common/Modal/ModalPage.tsx
  src/components/common/Modal/index.tsx
  src/stories/Modal.stories.tsx
Labels: Feat

#67 [57] Tab 컴포넌트 구현
  src/components/common/Tabs/TabBody.tsx
  src/components/common/Tabs/TabHeader.tsx
  src/components/common/Tabs/TabItem.tsx
  src/components/common/Tabs/TabsProvider.tsx
  src/components/common/Tabs/index.tsx
  src/constants/design.ts
  src/hooks/useDelayUnmount.ts
  src/stories/Tabs.stories.tsx
Labels: Feat

#71 [70] 피드 List Item 컴포넌트 구현
  src/components/feed/FeedFooterItem.tsx
  src/components/feed/FeedListItem.tsx
  src/stories/components/FeedFooterItem.stories.tsx
  src/stories/components/FeedListItem.stories.tsx
Labels: Feat

#79 [63] `styled-components`에서 `emotion`으로 전환
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/common/Avatar.tsx
  src/components/common/Button.tsx
  src/components/common/Container.tsx
  src/components/common/Flex.tsx
  src/components/common/Image/index.tsx
  src/components/common/Skeleton.tsx
  src/components/common/Text.tsx
  src/components/input/Input.tsx
  src/stories/Button.stories.tsx
  src/stories/Container.stories.tsx
  src/stories/Flex.stories.tsx
  src/stories/Icon.stories.tsx
  src/stories/Skeleton.stories.tsx
  src/stories/Text.stories.tsx
Labels: Refactor, Chore

#53 [34] Loading 컴포넌트 구현
  src/components/loading/CircleLoading.tsx
  src/stories/components/CircleLoading.stories.ts
Labels: Feat

#91 [90] CircleLoading컴포넌트의 story props 수정
  src/stories/components/CircleLoading.stories.ts
Labels: Docs

#93 [92] 페이지 라우팅
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/ErrorPage.tsx
  src/pages/FeedPage.tsx
  src/pages/LoginPage.tsx
  src/pages/PostPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SearchPage.tsx
  src/pages/SignupPage.tsx
  src/router.tsx
Labels: Chore

#89 [76] Image 컴포넌트 수정
  src/components/common/Image/index.tsx
  src/stories/components/Image.stories.tsx
Labels: Refactor

#87 [78] 재사용 컴포넌트 개선
  .stylelintrc.js
  src/components/common/Box.tsx
  src/components/common/Button.tsx
  src/components/common/CommonStyle.tsx
  src/components/common/Container.tsx
  src/components/common/Flex.tsx
  src/components/common/Skeleton.tsx
  src/components/common/Text.tsx
  src/stories/Box.stories.tsx
  src/stories/Button.stories.tsx
  src/stories/Container.stories.tsx
  src/stories/Flex.stories.tsx
  src/stories/Text.stories.tsx
  src/types/design/common.ts
  src/utils/handleResponsiveStyle.ts
Labels: Refactor

#98 Chore: styled-components 사용 금지 규칙 비활성화
  .eslintrc.cjs
Labels: Chore

#100 [99] 스타일 린트 에러 발생 파일 추적 및 수정
  src/components/common/Button.tsx
  src/components/common/Container.tsx
  src/components/common/Flex.tsx
  src/components/common/NavBar/index.tsx
  src/components/common/Skeleton.tsx
  src/components/common/Text.tsx
  src/components/feed/FeedListItem.tsx
  src/stories/components/CircleLoading.stories.ts
Labels: Fix, Refactor

#82 [74] 로그인 페이지의 Template에서 Login Form 컴포넌트 구현
  src/components/input/Input.tsx
  src/components/loginForm/LoginForm.tsx
  src/stories/components/Login.stories.tsx
Labels: Feat

#96 Fix: `VITE_` 접두어 추가
  src/api/axios.ts
Labels: Fix

#83 [75] 회원가입 Template의 Signup Form 컴포넌트 구현
  src/components/signupForm/SignupForm.tsx
  src/stories/components/SignupForm.stories.tsx
Labels: Feat

#86 [77] 프로필 페이지 구현
  public/img/200X200.png
  src/api/axios.ts
  src/components/UserListItem.tsx
  src/components/templates/ProfileSkeleton.tsx
  src/components/templates/ProfileTemplate.tsx
  src/components/uploadImage/ProfileImageUpload.tsx
  src/hooks/api/auth/useAuth.ts
  src/hooks/api/follow/useCreateFollow.ts
  src/hooks/api/follow/useDeleteFollow.ts
  src/hooks/api/index.ts
  src/hooks/api/users/useGetUser.ts
  src/hooks/api/users/useGetUsers.ts
  src/hooks/api/users/useUploadPhoto.ts
  src/pages/ProfilePage.tsx
  src/stories/ProfileTemplate.stories.tsx
Labels: Feat

#111 [107] 잘못 마이그레이션된 emotion 공통 로직 수정
  .eslintrc.cjs
  src/components/RadioGroup/Radio.tsx
  src/components/common/Box.tsx
  src/components/common/Button.tsx
  src/components/common/CommonStyle.tsx
  src/components/common/Container.tsx
  src/components/common/Flex.tsx
  src/components/common/Logo.tsx
  src/components/common/Modal/ModalBody.tsx
  src/components/common/Modal/ModalHeader.tsx
  src/components/common/Modal/ModalPage.tsx
  src/components/common/Modal/index.tsx
  src/components/common/NavBar/index.tsx
  src/components/common/Skeleton.tsx
  src/components/common/Tabs/TabBody.tsx
  src/components/common/Tabs/TabItem.tsx
  src/components/common/Text.tsx
  src/components/feed/FeedListItem.tsx
  src/components/loading/CircleLoading.tsx
  src/components/templates/ProfileSkeleton.tsx
  src/components/templates/ProfileTemplate.tsx
  src/components/uploadImage/ProfileImageUpload.tsx
  src/pages/ProfilePage.tsx
  src/stories/Modal.stories.tsx
  src/stories/Tabs.stories.tsx
Labels: Fix

#88 [85] Input 컴포넌트 Refactor
  src/components/input/Input.tsx
  src/components/loginForm/LoginForm.tsx
  src/constants/regex.ts
  src/stories/components/Input.stories.tsx
  src/utils/regex.ts
Labels: Refactor

#112 [109] StyledComponent addon 설치 및 연결
  .storybook/main.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
Labels: Chore

#108 [103] 검색 페이지 템플릿 구현
  src/components/FeedListSkeleton.tsx
  src/components/SearchTemplate.tsx
  src/components/UserListSkeleton.tsx
  src/components/common/Tabs/TabItem.tsx
  src/components/feed/FeedFooterItem.tsx
  src/components/feed/FeedListItem.tsx
  src/components/search/FollowButton.tsx
  src/components/search/ListItem.tsx
  src/components/search/SearchBar.tsx
  src/components/search/UserList.tsx
  src/components/search/UserListItem.tsx
  src/components/search/UserProfileBox.tsx
  src/stories/FollowButton.stories.tsx
  src/stories/SearchTemplate.stories.tsx
  src/stories/UserListItem.stories.tsx
  src/stories/UserProfileBox.stories.tsx
  src/types/common.ts
Labels: Feat

#101 [80] 서비스 모달 폼 구현
  package-lock.json
  package.json
  src/Test.tsx
  src/atoms/postModalState.ts
  src/components/BasicPostModal.tsx
  src/components/ContentEditableDiv.tsx
  src/components/MogakPostModal.tsx
  src/components/PostButton.tsx
  src/components/RadioGroup/Radio.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/ReviewForm.tsx
  src/components/ReviewPostModal.tsx
  src/components/common/Modal/ModalFooter.tsx
  src/components/common/Modal/ModalHeader.tsx
  src/components/common/Modal/ModalPage.tsx
  src/components/common/Modal/index.tsx
  src/hooks/usePostContent.ts
  src/index.css
  src/router.tsx
Labels: Feat

#116 [94] Feed List Input 컴포넌트 구현
  src/components/feed/FeedContentEditable.tsx
  src/components/feed/FeedListInput.tsx
  src/components/feed/FeedListItem.tsx
  src/hooks/useFeedContent.tsx
  src/stories/components/FeedListInput.stories.tsx
Labels: Feat

#56 [43] PostCommentListItem 컴포넌트 구현
  src/components/postComment/PostCommentListItem.tsx
  src/stories/components/PostCommentListItem.stories.tsx
Labels: Feat

#68 [49] DropDown 컴포넌트 구현
  src/components/dropDown/DropDown.tsx
  src/hooks/useDetectClose.tsx
  src/stories/components/DropDown.stories.tsx
Labels: Feat

#118 [114] Post 커스텀 훅 구현
  src/constants/post.ts
  src/hooks/api/post/useCreatePost.ts
  src/hooks/api/post/useDeletePost.ts
  src/hooks/api/post/useGetPostDetail.ts
  src/hooks/api/post/useGetPosts.ts
  src/hooks/api/post/useGetPostsByUser.ts
  src/hooks/api/post/useUpdatePost.ts
  src/types/api/posts.ts
  src/types/common.ts
Labels: Feat

#119 [113] vercel 배포 설정
  .gitignore
  src/hooks/api/comment/useCreateComment.ts
  src/hooks/api/comment/useDeleteComment.ts
  src/hooks/api/notification/useCreateNotification.ts
  src/hooks/api/notification/useGetNotification.ts
  src/hooks/api/notification/useReadNotification.ts
  src/hooks/api/search/useSearchAll.ts
  src/hooks/api/search/useSearchUsers.ts
  tsconfig.json
  vercel.json
Labels: Chore

#115 [102] 로그인 페이지 구현
  src/App.tsx
  src/components/input/Input.tsx
  src/components/loginForm/LoginForm.tsx
  src/components/templates/LoginTemplate.tsx
  src/hooks/api/auth/useLogin.ts
  src/pages/LoginPage.tsx
  src/recoil/login/atoms.ts
  src/router.tsx
  src/types/api/status.ts
Labels: Feat

#120 [106] 회원가입 페이지 구현
  src/components/input/Input.tsx
  src/components/loading/CircleLoading.tsx
  src/components/signupForm/SignupForm.tsx
  src/components/templates/SignupTemplate.tsx
  src/hooks/api/signup/useSignup.ts
  src/pages/SignupPage.tsx
  src/router.tsx
  src/stories/components/CircleLoading.stories.ts
Labels: Feat

#55 [32] DMItem 컴포넌트 구현
  src/components/directMessage/DMItem.tsx
  src/stories/components/DMItem.stories.ts
Labels: Feat

#134 [130] 네비게이션바 수정, 로그인 로직 추가, 기본 이미지 변경
  public/img/200X200.png
  public/img/default_profile.svg
  src/App.tsx
  src/components/common/Image/index.tsx
  src/components/common/NavBar/index.tsx
  src/components/uploadImage/ProfileImageUpload.tsx
  src/hooks/api/auth/useLogin.ts
  src/hooks/api/signup/useSignup.ts
  src/pages/ChatPage.tsx
  src/recoil/login/atoms.ts
  src/router.tsx
Labels: Fix

#138 [136] 로그아웃 훅
  src/components/common/NavBar/index.tsx
  src/hooks/api/auth/useLogout.ts
Labels: Feat

#123 [121] 사용자 목록 리스트 템플릿 구현
  src/components/templates/UserStateListTemplate.tsx
  src/components/userListItem/UserStateListItem.tsx
  src/hooks/api/users/useGetUsers.ts
  src/pages/UserStateListPage.tsx
  src/stories/UserStateListTemplate.stories.tsx
  src/stories/components/UserStateListItem.stories.tsx
Labels: Feat

#143 [135] 내 정보 변경 기능 추가
  src/components/input/Input.tsx
  src/components/profile/ImageUploadForm.tsx
  src/components/profile/NameChangeForm.tsx
  src/components/profile/PasswordChangeForm.tsx
  src/components/templates/ProfileTemplate.tsx
  src/hooks/api/settings/useUpdateName.ts
  src/hooks/api/settings/useUpdatePassword.ts
  src/pages/ProfilePage.tsx
Labels: Feat

#117 [81] Feed Template & Post Page 구현
  src/components/FeedPageTemplate.tsx
  src/components/dropDown/DropDown.tsx
  src/components/feed/FeedContentEditable.tsx
  src/components/feed/FeedListInput.tsx
  src/components/feed/FeedListItem.tsx
  src/components/post/Post.tsx
  src/components/templates/PostTemplate.tsx
  src/hooks/api/post/useDeletePost.tsx
  src/hooks/api/post/useGetPost.tsx
  src/hooks/api/post/useUpdatePost.tsx
  src/pages/FeedPage.tsx
  src/pages/PostPage.tsx
  src/stories/components/FeedPageTemplate.stories.tsx
  src/stories/components/PostTemplate.stories.tsx
Labels: Feat

#148 [146] 검색, 프로필 오류 해결
  src/components/FeedPageTemplate.tsx
  src/components/SearchTemplate.tsx
  src/components/feed/FeedListInput.tsx
  src/components/feed/FeedListItem.tsx
  src/components/templates/ProfileTemplate.tsx
  src/pages/SearchPage.tsx
  src/types/api/search.ts
  src/types/common.ts
Labels: Fix

#152 [149] 채팅 페이지 프로필 사진 클릭시 프로필 페이지로 이동하는 기능 추가
  src/components/directMessage/DMItem.tsx
  src/components/templates/DMListTemplate.tsx
  src/pages/PresonalMessagePage.tsx
Labels: Feat

#156 [153] 메시지 읽음 처리 기능 추가
  src/components/PersonalConversation.tsx
  src/components/PersonalMessage.tsx
  src/components/directMessage/DMItem.tsx
  src/hooks/api/conversation/useMessageSeen.ts
Labels: Feat

#159 [151] 포스트 모달 포스트 작성 api 연결
  src/Test.tsx
  src/components/PostButton.tsx
  src/components/ReviewForm.tsx
  src/components/common/NavBar/index.tsx
  src/components/common/Select.tsx
  src/components/postModal/BasicPostModal.tsx
  src/components/postModal/MogakPostModal.tsx
  src/components/postModal/PostTypeButton.tsx
  src/components/postModal/ReviewPostModal.tsx
  src/recoil/postModal/atoms.ts
  src/types/common.ts
Labels: Feat

#160 [141] 가입자 목록 수정
  src/App.tsx
  src/components/UserStateListSideBar.tsx
  src/components/templates/UserStateListTemplate.tsx
  src/components/userListItem/UserStateListItem.tsx
Labels: Feat, Refactor

#162 [145] 포스트 워킹 스팟 구현
  src/components/FeedPageTemplate.tsx
  src/components/WorkSpotSelector.tsx
  src/components/WorkingSpotIcon.tsx
  src/components/common/Select.tsx
  src/components/common/Tooltip.tsx
  src/components/feed/FeedListInput.tsx
  src/components/feed/FeedListItem.tsx
  src/hooks/useTooltip.ts
  src/pages/FeedPage.tsx
  src/types/common.ts
  src/utils/getPositionStyle.ts
Labels: Feat

#167 [164] 색상 변경
  src/components/PersonalMessage.tsx
  src/components/templates/UserStateListTemplate.tsx
  src/components/userListItem/UserStateListItem.tsx
Labels: Refactor

#169 [168] 입력 글자수에 대해 길이를 제한하는 maxLength props및 기능 추가
  src/components/input/Input.tsx
  src/components/signupForm/SignupForm.tsx
Labels: Refactor

#171 [165] Avatar 수정
  src/components/UserListItem.tsx
  src/components/common/Avatar.tsx
  src/components/feed/FeedListInput.tsx
  src/components/feed/FeedListItem.tsx
  src/components/post/Post.tsx
  src/components/post/PostCommentInput.tsx
  src/components/postComment/PostCommentListItem.tsx
  src/components/postModal/BasicPostModal.tsx
  src/components/search/UserListItem.tsx
  src/components/templates/PostTemplate.tsx
  src/components/templates/ProfileTemplate.tsx
Labels: Feat, Refactor

#172 [170] 메시지 창의 높이 수정
  src/components/PersonalConversation.tsx
Labels: Refactor

#174 [173] 프로필 페이지의 메시지 보내기 버튼 활성화
  src/components/templates/ProfileTemplate.tsx
Labels: Refactor

#176 [144] 포스트 수정 구현
  src/components/common/Button.tsx
  src/components/templates/PostEditTemplate.tsx
  src/pages/PostEditPage.tsx
  src/router.tsx
Labels: Feat

#177 [166] 로고 수정
  package-lock.json
  package.json
  src/components/FeedPageTemplate.tsx
  src/components/PostButton.tsx
  src/components/common/Logo.tsx
  src/components/feed/FeedListItem.tsx
  src/components/post/PostCommentInput.tsx
  src/components/search/FollowButton.tsx
  src/components/templates/UserStateListTemplate.tsx
  src/pages/PostPage.tsx
  src/pages/SearchPage.tsx
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.json
  vite.config.ts
Labels: Feat, Refactor, Chore

#184 [178] 메시지, 댓글, 팔로우 알림 생성 로직
  src/components/FeedPageTemplate.tsx
  src/components/common/NavBar/index.tsx
  src/components/feed/FeedListInput.tsx
  src/components/notification/NotificationItem.tsx
  src/components/postComment/PostCommentListItem.tsx
  src/components/postModal/PostTypeButton.tsx
  src/components/templates/MessageSendingTemplate.tsx
  src/components/templates/NotificationSkeleton.tsx
  src/components/templates/NotificationTemplate.tsx
  src/components/templates/PostTemplate.tsx
  src/components/templates/ProfileTemplate.tsx
  src/components/templates/RequiredLoginTemplate.tsx
  src/hooks/api/comment/useCreateComment.ts
  src/hooks/api/follow/useCreateFollow.ts
  src/hooks/api/notification/useCreateNotification.ts
  src/pages/FeedPage.tsx
  src/pages/NotificationPage.tsx
  src/pages/PostPage.tsx
  src/pages/ProfilePage.tsx
  src/router.tsx
Labels: Feat

#188 [187] vercel 빌드 에러 일부 fix
  src/components/FeedListSkeleton.tsx
  src/components/SearchTemplate.tsx
  src/components/UsersLink.tsx
  src/components/WorkingSpotIcon.tsx
  src/components/post/Post.tsx
  src/components/search/FollowButton.tsx
  src/components/search/SearchBar.tsx
  src/components/search/UserList.tsx
  src/components/search/UserListItem.tsx
  src/components/search/UserProfileBox.tsx
  src/pages/FeedPage.tsx
  src/pages/SearchPage.tsx
  src/types/common.ts
Labels: Fix

#189 [186] 회원가입, 로그인, 채팅 페이지 레이아웃 수정
  src/components/PersonalConversation.tsx
  src/components/input/Input.tsx
  src/components/loginForm/LoginForm.tsx
  src/components/signupForm/SignupForm.tsx
  src/components/templates/DMListTemplate.tsx
  src/components/templates/LoginTemplate.tsx
  src/components/templates/MessageSendingTemplate.tsx
  src/components/templates/SignupTemplate.tsx
Labels: Refactor

#191 [190] 파일 삭제
  src/pages/UserStateListPage.tsx
Labels: Fix

#192 [161] 현재 접속중인 사용자 목록 구현
  src/components/UserStateListSideBar.tsx
  src/components/templates/UserStateListTemplate.tsx
  src/hooks/api/users/useGetOnlineUsers.ts
Labels: Feat

#193 [182] 검색 페이지 사용자 follow 로직 추가
  src/components/search/FollowButton.tsx
  src/components/search/UserList.tsx
  src/components/search/UserListItem.tsx
  src/components/templates/SearchTemplate.tsx
  src/hooks/api/search/useSearchAll.ts
  src/hooks/api/search/useSearchUsers.ts
  src/pages/SearchPage.tsx
  src/types/common.ts
Labels: Feat

#198 [183] 포스트 모달 이미지 첨부 기능 추가
  src/components/FeedListSkeleton.tsx
  src/components/WorkSpotSelector.tsx
  src/components/WorkingSpotIcon.tsx
  src/components/common/NavBar/index.tsx
  src/components/feed/FeedListInput.tsx
  src/components/postModal/BasicPostModal.tsx
  src/pages/FeedPage.tsx
Labels: Feat

#199 [197] 포스트 수정, 프로필, 알림 페이지 수정
  src/components/notification/NotificationItem.tsx
  src/components/templates/ProfileTemplate.tsx
  src/pages/PostEditPage.tsx
Labels: Fix

#201 [196] 온라인 사용자 호출 시간 간격 수정
  src/components/UserStateListSideBar.tsx
Labels: Refactor

#202 [200] FeedFooterItem props 수정
  src/components/feed/FeedFooterItem.tsx
  src/components/feed/FeedListItem.tsx
  src/components/feed/LikeItem.tsx
Labels: Fix

#204 [203] FeedFooterItem에 잘못된 props 입력 수정
  src/components/post/Post.tsx
Labels: Fix

#206 [205] 포스트 파싱에 실패한 경우에 대한 예외 처리
  src/components/templates/ProfileTemplate.tsx
Labels: Fix

#208 [175] 채팅 페이지 수정
  src/components/PersonalConversation.tsx
  src/components/PersonalMessage.tsx
  src/components/templates/DMListTemplate.tsx
  src/components/templates/MessageSendingTemplate.tsx
  src/pages/PresonalMessagePage.tsx
Labels: Refactor

#213 [211] 온라인 사용자 호출 수정
  src/api/axios.ts
  src/hooks/api/index.ts
  src/hooks/api/users/useGetOnlineUsers.ts
  src/hooks/api/users/useGetUsers.ts
Labels: Refactor

#215 [214] 이메일 유효성 검사 문자 패턴 수정
  src/constants/regex.ts
Labels: Refactor

#105 [104] CircleLoading 컴포넌트 수정
  src/components/loading/CircleLoading.tsx
  src/components/loginForm/LoginForm.tsx
  src/components/templates/DMListTemplate.tsx
  src/stories/components/CircleLoading.stories.ts
Labels: Refactor

#216 [209] 다크모드 수동 토글 기능 추가
  index.html
  src/components/common/NavBar/ThemeSelectButton.tsx
  src/components/common/NavBar/ThemeSelectModal.tsx
  src/components/common/NavBar/index.tsx
  src/components/dropDown/DropDown.tsx
Labels: Feat

#219 [212] Header 반응형으로 변경
  package-lock.json
  package.json
  src/components/common/NavBar/index.tsx
Labels: Style, Refactor

#220 [210] 온라인 바 UI 반응형으로 수정
  src/App.tsx
  src/components/templates/UserStateListTemplate.tsx
  src/components/userListItem/UserStateListItem.tsx
Labels: Style

#221 [218] UI 수정
  src/components/directMessage/DMItem.tsx
  src/components/templates/DMListTemplate.tsx
  src/components/templates/MessageSendingTemplate.tsx
  src/components/userListItem/UserStateListItem.tsx
Labels: Refactor

#226 [225] 채팅 목록 item의 컨테이너 border를 삭제, box-shadow로 수정
  src/components/directMessage/DMItem.tsx
  src/components/templates/DMListTemplate.tsx
Labels: Refactor

#228 [224] Search 페이지 follow/unfollow, 좋아요/취소 기능 로그인 예외처리
  src/components/RequiredLoginModal.tsx
  src/components/common/Modal/index.tsx
  src/components/common/NavBar/index.tsx
  src/components/feed/LikeItem.tsx
  src/components/search/FollowButton.tsx
  src/components/templates/RequiredLoginTemplate.tsx
  src/components/templates/SearchTemplate.tsx
  src/pages/SearchPage.tsx
  src/recoil/loginModal/atoms.ts
Labels: Fix

#230 [227] 채팅 페이지 수정
  src/components/PersonalConversation.tsx
  src/components/PersonalMessage.tsx
  src/components/templates/DMListTemplate.tsx
  src/components/templates/MessageSendingTemplate.tsx
  src/pages/PresonalMessagePage.tsx
Labels: Refactor

#232 [229] 포스트 작성 모달 로그인 예외처리
  src/components/ModalPostButton.tsx
  src/components/common/NavBar/index.tsx
  src/components/feed/LikeItem.tsx
Labels: Fix

#236 [231] textarea ui 수정
  src/components/MessageSending.tsx
Labels: Design

#235 [223] 전역 CSS 수정
  src/components/FeedListSkeleton.tsx
  src/components/FeedPageTemplate.tsx
  src/components/PersonalConversation.tsx
  src/components/PersonalMessage.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/UserListSkeleton.tsx
  src/components/UsersLink.tsx
  src/components/WorkingSpotIcon.tsx
  src/components/common/Button.tsx
  src/components/common/CommonStyle.tsx
  src/components/common/Logo.tsx
  src/components/common/Modal/ModalBody.tsx
  src/components/common/Modal/index.tsx
  src/components/common/NavBar/ThemeSelectModal.tsx
  src/components/common/Select.tsx
  src/components/common/Tabs/TabItem.tsx
  src/components/common/Tooltip.tsx
  src/components/directMessage/DMItem.tsx
  src/components/dropDown/DropDown.tsx
  src/components/feed/FeedListInput.tsx
  src/components/feed/FeedListItem.tsx
  src/components/feed/LikeItem.tsx
  src/components/input/Input.tsx
  src/components/loginForm/LoginForm.tsx
  src/components/notification/NotificationItem.tsx
  src/components/post/Post.tsx
  src/components/post/PostCommentInput.tsx
  src/components/postComment/PostCommentListItem.tsx
  src/components/postModal/MogakPostModal.tsx
  src/components/profile/NameChangeForm.tsx
  src/components/profile/PasswordChangeForm.tsx
  src/components/search/FollowButton.tsx
  src/components/search/ListItem.tsx
  src/components/search/SearchBar.tsx
  src/components/search/UserList.tsx
  src/components/search/UserProfileBox.tsx
  src/components/templates/DMListTemplate.tsx
  src/components/templates/ErrorTemplate.tsx
  src/components/templates/LoginTemplate.tsx
  src/components/templates/MessageSendingTemplate.tsx
  src/components/templates/NotFoundTemplate.tsx
  src/components/templates/NotificationTemplate.tsx
  src/components/templates/PostEditTemplate.tsx
  src/components/templates/PostTemplate.tsx
  src/components/templates/ProfileSkeleton.tsx
  src/components/templates/ProfileTemplate.tsx
  src/components/templates/RequiredLoginTemplate.tsx
  src/components/templates/SearchTemplate.tsx
  src/components/templates/SignupTemplate.tsx
  src/components/templates/UnauthorizedTemplate.tsx
  src/components/templates/UserStateListTemplate.tsx
  src/components/userListItem/UserStateListItem.tsx
  src/main.tsx
  src/stories/Modal.stories.tsx
  src/styles/colors.css
  src/styles/constants.css
  src/styles/index.css
  src/styles/reset.css
  src/styles/scroll.css
Labels: Style

#240 [234] 온라인 사용자 사이드 바 레이아웃 수정
  src/components/UserStateListSideBar.tsx
  src/components/search/FollowButton.tsx
  src/components/templates/UserStateListTemplate.tsx
  src/components/userListItem/UserStateListItem.tsx
  src/hooks/api/search/useSearchUsers.ts
Labels: Fix

#241 [239] 페이지별 title 설정, 파비콘 설정
  index.html
  package-lock.json
  package.json
  public/favicon.svg
  src/App.tsx
  src/pages/ChatPage.tsx
  src/pages/DMListPage.tsx
  src/pages/FeedPage.tsx
  src/pages/LoginPage.tsx
  src/pages/NotificationPage.tsx
  src/pages/PostEditPage.tsx
  src/pages/PostPage.tsx
  src/pages/PresonalMessagePage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SearchPage.tsx
  src/pages/SignupPage.tsx
Labels: Feat

#243 [242] 피드 페이지 좋아요, 카공 장소 UI 수정
  src/components/WorkingSpotIcon.tsx
  src/components/feed/LikeItem.tsx
  src/components/userListItem/UserStateListItem.tsx
Labels: Style

#245 [244] textarea color 수정
  src/components/MessageSending.tsx
Labels: Refactor

#247 [246] Post 예외처리 제거, 로그아웃시 post comment input 접근 불가능하게 수정
  src/components/FeedPageTemplate.tsx
  src/components/feed/FeedListInput.tsx
  src/components/post/PostCommentInput.tsx
  src/components/templates/PostTemplate.tsx
Labels: Refactor

#251 [250] 프로필 이미지 변경시 갱신되지 않는 문제 해결
  src/components/profile/ImageUploadForm.tsx
  src/components/profile/NameChangeForm.tsx
  src/components/profile/PasswordChangeForm.tsx
  src/hooks/api/settings/useUpdateName.ts
  src/hooks/api/users/useUploadPhoto.ts
Labels: Fix

#253 [252] 팔로우 알림 연결
  src/components/search/FollowButton.tsx
Labels: Feat

#254 [237] 채팅 목록에서 Badge 삭제
  src/components/directMessage/DMItem.tsx
  src/components/templates/DMListTemplate.tsx
  src/stories/components/DMItem.stories.ts
Labels: Refactor

#256 [255] 대화창에 새로운 데이터가 들어오면 scroll이 최하단으로 이동
  src/components/PersonalConversation.tsx
Labels: Feat

#258 [257] 알림 페이지 수정
  src/components/feed/LikeItem.tsx
  src/components/notification/NotificationItem.tsx
  src/components/templates/MessageSendingTemplate.tsx
  src/components/templates/NotificationSkeleton.tsx
  src/components/templates/NotificationTemplate.tsx
  src/components/templates/PostTemplate.tsx
Labels: Fix

#260 [259] 메시지 전송 훅 수정
  src/components/templates/MessageSendingTemplate.tsx
  src/hooks/api/conversation/useCreateMessage.ts
Labels: Fix

#263 [262] 비로그인시 알림 fetch 제한
  src/pages/NotificationPage.tsx
Labels: Fix
